const Data = {
  faculties:[
    {
      name:"kuthesir",
      photo:"Asst_Secretory.webp",
      post:"hod" 
    },
    {
      name:"kuthesir",
      photo:"Asst_Secretory.webp",
      post:"hod" 
    },
    {
      name:"kuthesir",
      photo:"Asst_Secretory.webp",
      post:"hod" 
    },
    {
      name:"kuthesir",
      photo:"Asst_Secretory.webp",
      post:"hod" 
    },
    {
      name:"kuthesir",
      photo:"Asst_Secretory.webp",
      post:"hod" 
    },
  ],
  teams:[
    {
      name:"Core",
      head:[
        {
          name:"aniket",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        },
        {
          name:"rasika",
          photo:"Asst_Secretory.webp",
          post:"hod" 

        }
      ],
      asst:[
        {
          name:"ritish",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        }
      ]
    },
    {
      name:"Core",
      head:[
        {
          name:"aniket",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        },
        {
          name:"rasika",
          photo:"Asst_Secretory.webp",
          post:"hod" 

        }
      ],
      asst:[
        {
          name:"ritish",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        }
      ]
    },
    {
      name:"Core",
      head:[
        {
          name:"aniket",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        },
        {
          name:"rasika",
          photo:"Asst_Secretory.webp",
          post:"hod" 

        }
      ],
      asst:[
        {
          name:"ritish",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        }
      ]
    },
    {
      name:"Core",
      head:[
        {
          name:"aniket",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        },
        {
          name:"rasika",
          photo:"Asst_Secretory.webp",
          post:"hod" 

        }
      ],
      asst:[
        {
          name:"ritish",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        }
      ]
    },
    {
      name:"Core",
      head:[
        {
          name:"aniket",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        },
        {
          name:"rasika",
          photo:"Asst_Secretory.webp",
          post:"hod" 

        }
      ],
      asst:[
        {
          name:"ritish",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        }
      ]
    },
    {
      name:"Core",
      head:[
        {
          name:"aniket",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        },
        {
          name:"rasika",
          photo:"Asst_Secretory.webp",
          post:"hod" 

        }
      ],
      asst:[
        {
          name:"ritish",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        }
      ]
    },
    {
      name:"Core",
      head:[
        {
          name:"aniket",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        },
        {
          name:"rasika",
          photo:"Asst_Secretory.webp",
          post:"hod" 

        }
      ],
      asst:[
        {
          name:"ritish",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        }
      ]
    },
    {
      name:"Core",
      head:[
        {
          name:"aniket",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        },
        {
          name:"rasika",
          photo:"Asst_Secretory.webp",
          post:"hod" 

        }
      ],
      asst:[
        {
          name:"ritish",
          photo:"Asst_Secretory.webp",
          post:"hod" 
        }
      ]
    },
  ],
};
